# Generated by Django 4.2.6 on 2023-11-20 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0188_inbound_hop_nodes'),
    ]

    operations = [migrations.RenameModel('InstanceLink', 'InstanceLinkBackup'), migrations.RenameModel('InstanceLinkReceptorAddress', 'InstanceLink')]
